version: "3"
services:
  app:
    image: $ECR_REGISTRY/beta8:$GITSHA
    container_name: hackathon_app
    ports:
      - "5001:5001"
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DATABASE_URL=$DATABASE_URL
