version: "3"
services:
  app:
    image: ECR_REGISTRY/beta8:GITHUB_SHA
    ports:
      - "5000:5001"
    environment:
      - SECRET_KEY=$$SECRET_ENV_VAR
      - DATABASE_URL=sqlite:///dev.db
    # volumes:
    #   - ./migrations:/var/www/migrations
    #   - ./migrate_and_seed.sh:/var/www/migrate_and_seed.sh
